---
- name: Déploiement de l'application
  hosts: all
  remote_user: "{{ ansible_user }}"

  tasks:
    - name: Inclure les variables utilisateur
      include_vars: vars.yml

    - name: Vérification de la présence du dossier
      stat:
        path: "{{ root_path }}"
      register: __application_path

    - name: Création du répertoire si il n'existe pas
      file:
        path: "{{ root_path }}"
        state: directory
      when: __application_path.stat.exists == false

    - name: Synchronisation des sources
      ansible.posix.synchronize:
        src: "{{ playbook_dir }}/../"
        dest: "{{ root_path }}/"
        recursive: yes
        delete: true
        times: yes
        perms: yes
        rsync_opts:
          - "--verbose"
          - "--exclude=.git"
          - "--exclude=.idea"
          - "--exclude=ansible"
